# Generated by Django 4.1.7 on 2023-03-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehivle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
