# Generated by Django 4.1.7 on 2023-03-09 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vehivle',
            new_name='Vehicle',
        ),
    ]
