# Generated by Django 4.1.7 on 2023-03-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_rename_vehivle_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('Two', 'Two'), ('Three', 'Three'), ('Four Wheelers', 'Four Wheelers')], default='Two', max_length=16),
            preserve_default=False,
        ),
    ]
